CREATE TABLE COZINHA (
	ID BIGINT(20) AUTO_INCREMENT,
	NOME VARCHAR(50),

	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO COZINHA (NOME) VALUES ('Lazer');
INSERT INTO COZINHA (NOME) VALUES ('Alimentação');
INSERT INTO COZINHA (NOME) VALUES ('Supermercado');